language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - 'pip install pipenv'
  - 'pipenv sync --dev'
script:
  - 'pipenv run pytest --cov=postcodeapi --cov-report html'
after_success:
  - 'coveralls'
