language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - 'pip install pipenv'
  - 'pipenv sync --dev'
  - 'pip install coveralls'
script:
  - 'pipenv run pytest'
after_success:
  - 'coveralls'
